layout_spectrum: 0.0212766
color:
  saturation: 0.6212766
  lightness: 0.7404255
  brandStrength: 0.9702128
  brandColors:
    - '#1E1E20'
    - '#B3B3B5'
    - '#E0E0E0'
    - '#5B5A5E'
  rhythmicContrast: 0.5
typography_spectrum: 0.3787234
name: Johnny Adventure
